In [4]:
# 1D Array

import numpy as np

a1 = np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [5]:
type(a1)

numpy.ndarray

In [6]:
a1.shape

(4,)

In [8]:
a1.size

4

In [11]:
# 2D Array

a2 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
type(a2)

numpy.ndarray

In [12]:
a2.shape

(2, 4)

In [13]:
a2.size

8

In [16]:
# 3D Arrays

a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [18]:
type(a3)

numpy.ndarray

In [19]:
a3.shape

(1, 3, 3)

In [20]:
a3.size

9

In [25]:
# Zero array - Create Array of zeros
# ZA = np.zeros(shape,datatype) By default the data type is float

# Default float datatype
za = np.zeros(3)
print(za)

# With datatype
za1 = np.zeros(3, int)
print(za1)

[0. 0. 0.]
[0 0 0]


In [32]:
z2 = np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
z2.shape

(3, 4)

In [28]:
z3 = np.zeros((3,4),dtype=int)
z3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
z4 = np.zeros((2,3),dtype=int)
z4

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
# Convert a 2x3 matrix into a 3x2 matrix

# Create a 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Get the dimensions of the original matrix
rows, cols = A.shape

# Create an empty matrix for the transpose
A_transpose = np.zeros((cols, rows))

# Fill the transpose matrix
for i in range(rows):
    for j in range(cols):
        A_transpose[j, i] = A[i, j]

print("Original Matrix (2x3):")
print(A)

print("\nTransposed Matrix (3x2):")
print(A_transpose)

Original Matrix (2x3):
[[1 2 3]
 [4 5 6]]

Transposed Matrix (3x2):
[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [42]:
# Transpose with predefined functions

matrix = np.array([[1,2,3],[4,5,6]])
matrix
transpose = matrix.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [58]:
# Full Arrays
# f1 = np.full([shape],value)

f1 = np.full(3,9)
f1

array([9, 9, 9])

In [66]:
# Shows the no of dimensions
f1.ndim

1

In [64]:
f2 = np.full([3,3],7)
print(f2)
f2.ndim

[[7 7 7]
 [7 7 7]
 [7 7 7]]


2

In [65]:
f3 = np.full([3,4,2],10)
print(f3)
f3.ndim

[[[10 10]
  [10 10]
  [10 10]
  [10 10]]

 [[10 10]
  [10 10]
  [10 10]
  [10 10]]

 [[10 10]
  [10 10]
  [10 10]
  [10 10]]]


3

In [71]:
# Arithmetic Operations on 1D Square Matrix

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
# c1 = a+b
# c2 = a-b
# c3 = a*b
# c4 = a/b
# c5 = a%b
# c6 = a^b
# c7 = a//b

#or 

c1 = np.add(a,b)
c2 = np.subtract(a,b)
c3 = np.multiply(a,b)
c4 = np.divide(a,b)
c5 = np.mod(a,b)
c6 = np.power(a,b)
c7 = np.floor_divide(a,b)

print(c1)
print(c2)
print(c3)
print(c4)
print(c5)
print(c6)
print(c7)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1 2 3 4]
[    1    64  2187 65536]
[0 0 0 0]


In [67]:
# Addition on non-square 1D matrix